menu:
  home: /
  archive: /archive
  submenu:
    google: //google.com/
    yahoo:  //yahoo.com/

extmenu:
  github: //github.com/
  hexo: //zespia.tw/hexo/
  theme:
    Pithiness:  //github.com/okoala/hexo-theme-pithiness
    Phase:  //github.com/tommy351/hexo-theme-phase
    Collect:  //github.com/beforeload/hexo-theme-collect

excerpt_link: Read More

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

## hexi only
tag_flickr: true
